package com.smproduce.scanner;

import android.app.*;import android.content.*;import android.graphics.Color;import android.hardware.Camera;import android.media.*;import android.os.*;import android.view.*;import android.widget.*;
import com.journeyapps.barcodescanner.DecoratedBarcodeView;import com.journeyapps.barcodescanner.BarcodeCallback;import com.journeyapps.barcodescanner.BarcodeResult;import com.journeyapps.barcodescanner.camera.CameraSettings;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity {
    enum Mode { CASE, PALLET }
    Mode mode=Mode.CASE; boolean front=true,busy=false,cameraScreen=false; LinearLayout root,results; TextView title,status; DecoratedBarcodeView barcodeView; final ExecutorService net=Executors.newSingleThreadExecutor();
    int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);} TextView tv(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(dp(8),dp(8),dp(8),dp(8));return v;}
    Button button(String s,int color){Button b=new Button(this);b.setText(s);b.setTextSize(20);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundColor(color);return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);build();}
    void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(24),dp(30),dp(24),dp(24));root.setBackgroundColor(Color.rgb(11,22,34));
        title=tv("SM PRODUCE · SCANNER",26);title.setTypeface(null,1);root.addView(title);
        LinearLayout modes=new LinearLayout(this);modes.setOrientation(LinearLayout.HORIZONTAL);Button c=button("CASE → PALLET",mode==Mode.CASE?Color.rgb(22,101,52):Color.rgb(52,65,85));Button p=button("PALLET → CASES",mode==Mode.PALLET?Color.rgb(22,101,52):Color.rgb(52,65,85));c.setOnClickListener(v->{mode=Mode.CASE;build();});p.setOnClickListener(v->{mode=Mode.PALLET;build();});modes.addView(c,new LinearLayout.LayoutParams(0,dp(64),1));modes.addView(p,new LinearLayout.LayoutParams(0,dp(64),1));root.addView(modes);
        status=tv(mode==Mode.CASE?"Scan a casecode to find its pallet":"Scan a pallet to show all its cases",18);root.addView(status);
        Button scan=button("SCAN BARCODE",Color.rgb(198,40,40));scan.setOnClickListener(v->launch());LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(82));sp.topMargin=dp(22);root.addView(scan,sp);
        Button camera=button(front?"Camera: FRONT":"Camera: REAR",Color.rgb(52,65,85));camera.setOnClickListener(v->{front=!front;build();});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(56));cp.topMargin=dp(12);root.addView(camera,cp);
        ScrollView scroll=new ScrollView(this);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);scroll.addView(results);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,0,1);rp.topMargin=dp(18);root.addView(scroll,rp);setContentView(root);}
    int cameraId(){try{int wanted=front?Camera.CameraInfo.CAMERA_FACING_FRONT:Camera.CameraInfo.CAMERA_FACING_BACK;for(int i=0;i<Camera.getNumberOfCameras();i++){Camera.CameraInfo x=new Camera.CameraInfo();Camera.getCameraInfo(i,x);if(x.facing==wanted)return i;}}catch(Exception ignored){}return 0;}
    void launch(){if(checkSelfPermission(android.Manifest.permission.CAMERA)!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.CAMERA},7001);return;}showCamera();}
    void showCamera(){try{cameraScreen=true;LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(Color.BLACK);barcodeView=new DecoratedBarcodeView(this);barcodeView.setStatusText("Place the barcode inside the frame");CameraSettings settings=new CameraSettings();settings.setRequestedCameraId(cameraId());barcodeView.getBarcodeView().setCameraSettings(settings);shell.addView(barcodeView,new LinearLayout.LayoutParams(-1,0,1));Button cancel=button("CANCEL",Color.rgb(52,65,85));cancel.setOnClickListener(v->closeCamera());shell.addView(cancel,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(shell);barcodeView.decodeSingle(new BarcodeCallback(){@Override public void barcodeResult(BarcodeResult result){if(result==null||result.getText()==null)return;String value=result.getText();runOnUiThread(()->{closeCamera();lookup(value.trim());});}});barcodeView.resume();}catch(Exception e){cameraScreen=false;build();fail("Camera unavailable: "+e.getMessage());}}
    void closeCamera(){if(barcodeView!=null){try{barcodeView.pause();}catch(Exception ignored){}barcodeView=null;}cameraScreen=false;build();}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grantResults){super.onRequestPermissionsResult(requestCode,permissions,grantResults);if(requestCode==7001){if(grantResults.length>0&&grantResults[0]==android.content.pm.PackageManager.PERMISSION_GRANTED)showCamera();else fail("Camera permission is required");}}
    @Override public void onBackPressed(){if(cameraScreen){closeCamera();return;}super.onBackPressed();}
    @Override protected void onPause(){if(barcodeView!=null)barcodeView.pause();super.onPause();}
    @Override protected void onResume(){super.onResume();if(cameraScreen&&barcodeView!=null)barcodeView.resume();}
    void lookup(String code){if(code.isEmpty()||busy)return;busy=true;status.setText("Checking "+code+"…");results.removeAllViews();net.execute(()->{try{String action=mode==Mode.CASE?"case_pallet_lookup":"pallet_cases_lookup";String key=mode==Mode.CASE?"case_serial":"pallet_id";String body="action="+URLEncoder.encode(action,"UTF-8")+"&"+key+"="+URLEncoder.encode(code,"UTF-8");HttpURLConnection c=(HttpURLConnection)new URL(BuildConfig.API_URL).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(6000);c.setReadTimeout(8000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");c.setRequestProperty("X-App-Token",BuildConfig.APP_TOKEN);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);JSONObject j=new JSONObject(sb.toString());runOnUiThread(()->show(code,j));}catch(Exception e){runOnUiThread(()->fail("Connection error: "+e.getMessage()));}});}
    void show(String code,JSONObject j){busy=false;if(j.optInt("ok",j.optBoolean("ok",false)?1:0)!=1){fail(j.optString("err",j.optString("error","Not found")));return;}status.setText("✓ "+code);tone(true);if(mode==Mode.CASE){String pallet=j.optString("pallet_id");JSONObject data=j.optJSONObject("data");if(pallet.isEmpty()&&data!=null)pallet=data.optString("pallet_id");TextView v=tv(pallet.isEmpty()?"PALLET NOT FOUND":"PALLET\n"+pallet,34);v.setTypeface(null,1);results.addView(v);}else{JSONArray a=j.optJSONArray("cases");if(a==null){JSONObject d=j.optJSONObject("data");if(d!=null)a=d.optJSONArray("cases");}if(a==null||a.length()==0){results.addView(tv("No cases in this pallet",22));return;}for(int i=0;i<a.length();i++){Object o=a.opt(i);String s=o instanceof JSONObject?((JSONObject)o).optString("case_serial",((JSONObject)o).optString("serial")):String.valueOf(o);results.addView(tv(s,22));}}}
    void fail(String m){busy=false;status.setText(m);tone(false);}
    void tone(boolean ok){try{ToneGenerator t=new ToneGenerator(AudioManager.STREAM_NOTIFICATION,90);t.startTone(ok?ToneGenerator.TONE_PROP_BEEP:ToneGenerator.TONE_PROP_NACK,200);new Handler(Looper.getMainLooper()).postDelayed(t::release,350);}catch(Exception ignored){}}
    @Override protected void onDestroy(){net.shutdownNow();super.onDestroy();}
}
